{
    "name": "GPS Tracking",
    "version": "1.0",
    "category": "Fleet Management",
    "summary": "Module to track GPS coordinates and display them on a map",
    "author": "Raúl Alejandro Rodríguez López",
    "website": "https://raulalejandro.com.mx",
    "depends": ["base_geoengine", "fleet", "base_approval"],
    "data": [
        "security/res_group_security.xml",
        "security/ir_rule_security.xml",
        "security/ir.model.access.csv",
        "report/gps_tracking_report_views.xml",
        "report/fleet_vehicle_loan_report_views.xml",
        "views/gps_geofence_views.xml",
        "views/gps_tracking_history_views.xml",
        "views/gps_tracking_device_views.xml",
        "views/geoengine_vector_layer_views.xml",
        "views/geoengine_raster_layer_views.xml",
        "views/gps_tracking_point_views.xml",
        "views/gps_tracking_templates.xml",
        "views/gps_tracking_menus.xml",
    ],
    "assets": {
        "web.assets_backend": ["gps_tracking/static/src/**/*"],
    },
    "installable": True,
    "application": True,
}
